# Generated by Django 6.0.3 on 2026-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_room_floor_alter_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='name',
        ),
        migrations.AddField(
            model_name='campus',
            name='number',
            field=models.CharField(default=0, max_length=27, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=999, verbose_name='Номер аудитории'),
        ),
    ]
